#!/bin/bash

# Dependencies: imagemagick, i3lock-color-git, scrot

IMAGE=$(mktemp).png
IMAGECOLOR=$(mktemp).png
TMPIMG=$(mktemp).xwd

#LOCKIMAGE is the Basname and will be extendet with _dark and png
#TEXT is the Text under the image

#Get Location from WLAN
LOCATION=$(/sbin/iwgetid -r)
case $LOCATION in
	"WLAN_001")
		LOCKIMAGE="lock"
		TEXT="Passwort Eingeben"
		;;
	"802.1X")
		LOCKIMAGE="lock2"
		TEXT="Computer gespert"
		;;
	"WIFIatWORK")
		LOCKIMAGE="stop"
		TEXT="you can\'t touch this"
		;;
	*)
		LOCKIMAGE="lock"
		TEXT="Passwort Eingeben"
		;;
esac	

# get path where the script is located
# its used for the lock icon
pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd`
popd > /dev/null
 

VALUE="60" #brightness value to compare to
$(xwd -root -out $TMPIMG -silent)
$(convert $TMPIMG $IMAGE)
#Crop Image to the center where the text an image will be, so you won't get white text on white space
$(convert $IMAGE -gravity Center -crop 50%\! $IMAGECOLOR)
COLOR=`convert $IMAGECOLOR -colorspace hsb -resize 1x1 txt:- | sed -E '/.*$/ {
                             N
                             s/.*\n.*([0-9]{1,2}[^\.])\.[0-9]+%\)$/\1/
                             }'`;
# pixelate: -scale 10% -scale 1000%
if [ "$COLOR" -gt "$VALUE" ]; then #white background image and black text
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=1.5 -resize 500.5% \
        -font Liberation-Sans -pointsize 26 -fill black -gravity center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/"${LOCKIMAGE}_dark.png" -gravity center -composite $IMAGE
    PARAM='--textcolor=00000000 --insidecolor=0000001c --ringcolor=0000003e \
        --linecolor=00000000 --keyhlcolor=ffffff80 --ringvercolor=ffffff00 \
        --insidevercolor=ffffff1c --ringwrongcolor=ffffff55 --insidewrongcolor=ffffff1c'
else #black
    convert $IMAGE -level 0%,100%,0.6 \
        -filter Gaussian -resize 20% -define filter:sigma=1.5 -resize 500.5% \
        -font Liberation-Sans -pointsize 26 -fill white -gravity center \
        -annotate +0+160 "$TEXT" \
        $SCRIPTPATH/"${LOCKIMAGE}.png" -gravity center -composite $IMAGE
    PARAM='--textcolor=ffffff00 --insidecolor=ffffff1c --ringcolor=ffffff3e \
        --linecolor=ffffff00 --keyhlcolor=00000080 --ringvercolor=00000000 \
        --insidevercolor=0000001c --ringwrongcolor=00000055 --insidewrongcolor=0000001c'
fi

# try to use a forked version of i3lock with prepared parameters
i3lock $PARAM -i $IMAGE > /dev/null 2>&1

if [ $? -ne 0 ]; then
    # We have failed, lets get back to stock one
    i3lock -i $IMAGE
fi

rm $IMAGE
